/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleGPT: typeof import('./theme/components/Aside/Widgets/ArticleGPT.vue')['default']
    Aside: typeof import('./theme/components/Aside/index.vue')['default']
    Banner: typeof import('./theme/components/Banner.vue')['default']
    Checkbox: typeof import('./theme/components/Tags/Checkbox.vue')['default']
    Clock: typeof import('./theme/components/Aside/Widgets/Clock.vue')['default']
    Comments: typeof import('./theme/components/Comments.vue')['default']
    Control: typeof import('./theme/components/Control.vue')['default']
    Copyright: typeof import('./theme/components/Copyright.vue')['default']
    Footer: typeof import('./theme/components/Footer.vue')['default']
    FooterLink: typeof import('./theme/components/FooterLink.vue')['default']
    Hello: typeof import('./theme/components/Aside/Widgets/Hello.vue')['default']
    LazyLoader: typeof import('./theme/components/LazyLoader.vue')['default']
    LinkCard: typeof import('./theme/components/Tags/LinkCard.vue')['default']
    LinkList: typeof import('./theme/components/List/LinkList.vue')['default']
    Loading: typeof import('./theme/components/Loading.vue')['default']
    Message: typeof import('./theme/components/Message.vue')['default']
    MobileMenu: typeof import('./theme/components/MobileMenu.vue')['default']
    Nav: typeof import('./theme/components/Nav.vue')['default']
    Player: typeof import('./theme/components/Player.vue')['default']
    PostList: typeof import('./theme/components/List/PostList.vue')['default']
    RightMenu: typeof import('./theme/components/RightMenu.vue')['default']
    Search: typeof import('./theme/components/Search.vue')['default']
    SiteData: typeof import('./theme/components/Aside/Widgets/SiteData.vue')['default']
    Tags: typeof import('./theme/components/Aside/Widgets/Tags.vue')['default']
    Toc: typeof import('./theme/components/Aside/Widgets/Toc.vue')['default']
    TypeBar: typeof import('./theme/components/List/TypeBar.vue')['default']
  }
}
